#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

# Source tutorial run functions
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
#canCompile || exit 0    # Dynamic code
runApplication blockMesh
#runApplication decomposePar
runApplication $(getApplication)


